version: '3.2'

services:

  mysql:
    build: 
        context: ./
        dockerfile: sql.Dockerfile
    image: studymanagement-db:latest
    restart: always
    ports: 
      - 3100:3306
    command: --init-file /data/application/studymanagement.sql
    hostname: mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_volume:/var/lib/mysql

  studymanagement:
    build: 
        context: ./
        dockerfile: Dockerfile
    image: studymanagement:latest
    ports:
      - 9010:8080
    depends_on: 
      - mysql
    restart: always
    env_file:
        - ./studymanagement.env
        
volumes:
  mysql_volume: